### ISSUE TITLE
v1.6 being only available for 1.20 and up

### ISSUE THREAD

**Issue by KingColton1** [okx-code/civmodern#10]
I'm not sure if that is intentional or not but I tried to run this mod assuming it can support 1.18 and above including 1.20.x but it seems like this version only support 1.20.x. Can v1.6 be supported from 1.18 and above rather than being only one version?

**Comment by okx-code** [comment]
No, maintaining support for multiple versions is very difficult due to the amount of internal Mojang changes there are between versions.
