### ISSUE TITLE
Radar causes rendering issues with some chat mods

### ISSUE THREAD

**Issue by squareblob** [okx-code/civmodern#3]
When radar is enabled and [AdvancedChat](https://www.curseforge.com/minecraft/mc-mods/advancedchat) mod is installed, all newly received messages start with fully opaque backgrounds. 

![image](https://user-images.githubusercontent.com/40185801/123199892-bce42180-d47d-11eb-92ef-0e6a13a81560.png)

**Comment by okx-code** [comment]
this is the bane of my existence

**Comment by okx-code** [comment]
i hate opengl

**Comment by walkersgaming** [comment]
Also happening with journeymap waypoints

![image](https://user-images.githubusercontent.com/14056973/125159524-d8cf0f00-e16f-11eb-9e5d-363dbd797b4e.png)
