### ISSUE TITLE
Middle-clicking the compacted item in the config generates only a ghost stack

### ISSUE THREAD

**Issue by Protonull** [okx-code/civmodern#30]
The `CompactedConfigScreen` invokes `player.addItem(ITEM.copy())` which was added in [7bd9105](https://github.com/okx-code/civmodern/commit/7bd9105bba990e6ab917e60c87375b23c8542a52#diff-4fb43b3ab41061a1832581ff63faa40edb0ef472c3607bbc30500d65284c3b4cR123), but I've just tested it and while it does produce an item, it immediately disappears if you open a chest or other container. Likewise, dropping them does nothing except decrement the item stack. I don't know whether this was an issue before.

**Comment by Protonull** [comment]
Just discovered the fix for this:
```diff
 if (player != null && isCursorOverItem((int) mouseX, (int) mouseY) && button == GLFW.GLFW_MOUSE_BUTTON_1 && player.isCreative()) {
-    player.addItem(ITEM.copy());
+    if (player.addItem(ITEM.copy())) {
+        final var listener = new net.minecraft.client.gui.screens.inventory.CreativeInventoryListener(this.minecraft);
+        player.inventoryMenu.addSlotListener(listener);
+        player.inventoryMenu.broadcastChanges();
+        player.inventoryMenu.removeSlotListener(listener);
+    }
     return true;
 }
```

This is because I noticed that, if I middle-clicked (cloned) the preview compacted item and then opened the creative inventory, it was no longer a ghost item. After adding a mixin that would print the names of the packets the client sends, I noticed that `net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket` would get sent for every compacted item you clone upon opening the creative inventory, and so the code above is pretty much verbatim what `net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen#init()` does.

**Comment by okx-code** [comment]
Not really concerned about fixing this because it was only ever supposed to be a developer thing
