### ISSUE TITLE
Auto Eat Macro Stops Jumping When Certain Menus are Open

### ISSUE THREAD

**Issue by yodabird19** [okx-code/civmodern#6]
The fix to [issue 5](https://github.com/okx-code/civmodern/issues/5) has largely worked, but I've discovered this one unusual case. 
Having certain menus (eg chat, pause, civmodern settings, but _not_ inventory) open changes the behavior of the auto eat macro; when the player's hunger drops to the amount that their held food item can replenish (IE when the macro is supposed to eat), instead the player stops jumping (but keeps moving forward) and does not eat.
This makes chatting or AFKing while using the macro more difficult.

Thanks!

**Comment by okx-code** [comment]
All civmodern does is press keybinds for you, something like this may be against the rule of "any other kind of modification allowing behavior which is impossible to achieve with a vanilla client"
