### ISSUE TITLE
Leaving/entering AN makes game bug out

### ISSUE THREAD

**Issue by JamesMacC8** [okx-code/civmodern#8]
dont know how to describe it but it makes the game lock your position and you cant change it. If you try and turn around it glitches you back to the front and you have to restart game to fix it

**Comment by okx-code** [comment]
This doesn't sound like an issue with civmodern, does this still happen when you remove the mod?

**Comment by JamesMacC8** [comment]
havent tried removing it but it started happening first AN entry since having the mod, has not happened for a while now though.
